import { BASE_UPGRADE_COSTS, SkillGroup, TeamType, Position } from "..";

export const AfterlifeUnited: TeamType = {
    title: 'Afterlife United',
    upgradeCosts: {'Team Reroll': 70, ...BASE_UPGRADE_COSTS},
    positionals: [
        {
            title: 'Zombie',
            ma: 4, st: 3, ag: 2, av: 8,
            normal: [SkillGroup.General],
            double: [SkillGroup.Increase, SkillGroup.Strength, SkillGroup.Agility, SkillGroup.Passing],
            startingSkills: ['Regeneration'],
            cost: 40,
            max: 16,
        },
        {
            title: 'Skeleton',
            ma: 5, st: 3, ag: 2, av: 7,
            normal: [SkillGroup.General],
            double: [SkillGroup.Increase, SkillGroup.Strength, SkillGroup.Agility, SkillGroup.Passing],
            startingSkills: ['Regeneration', 'Thick Skull'],
            cost: 40,
            max: 16,
        },
        {
            title: 'Ghoul',
            ma: 7, st: 3, ag: 3, av: 7,
            normal: [SkillGroup.General, SkillGroup.Agility],
            double: [SkillGroup.Increase, SkillGroup.Strength, SkillGroup.Passing],
            startingSkills: ['Dodge'],
            cost: 70,
            max: 4,
        },
        {
            title: 'Wight',
            ma: 6, st: 3, ag: 3, av: 8,
            normal: [SkillGroup.General, SkillGroup.Strength],
            double: [SkillGroup.Increase, SkillGroup.Agility, SkillGroup.Passing],
            startingSkills: ['Block', 'Regeneration'],
            cost: 90,
            max: 2,
        },
        {
            title: 'Flesh Golem',
            ma: 4, st: 4, ag: 2, av: 9,
            normal: [SkillGroup.General, SkillGroup.Strength],
            double: [SkillGroup.Increase, SkillGroup.Agility, SkillGroup.Passing],
            startingSkills: ['Regeneration', 'Stand Firm', 'Thick Skull'],
            cost: 110,
            max: 2,
        },
        {
            title: 'Werewolf',
            ma: 8, st: 3, ag: 3, av: 8,
            normal: [SkillGroup.General, SkillGroup.Agility],
            double: [SkillGroup.Increase, SkillGroup.Strength, SkillGroup.Passing],
            startingSkills: ['Claw', 'Frenzy', 'Regeneration'],
            cost: 120,
            max: 2,
        },
        {
            title: 'Mummy',
            ma: 3, st: 5, ag: 1, av: 9,
            normal: [SkillGroup.Strength],
            double: [SkillGroup.General, SkillGroup.Increase, SkillGroup.Agility, SkillGroup.Passing],
            startingSkills: ['Mighty Blow', 'Regeneration'],
            cost: 110,
            max: 2,
        },
    ],
}